### ISSUE TITLE
Dead link in "Why Pay For Search"

### ISSUE THREAD

**Issue by sawatkins** [kagisearch/kagi-docs#116]
### Relevant Page(s)

https://help.kagi.com/kagi/why-kagi/why-pay-for-search.html

### Description

The second sentence in the page [Why Pay For Search](https://help.kagi.com/kagi/why-kagi/why-pay-for-search.html) has a dead link to a deleted twitter post. You can see the archived tweet [here](https://web.archive.org/web/20230607035925/https://twitter.com/MIBElashri/status/1640947867949973504). 

Since this is a prominent page in the docs, I wanted to ask your thoughts before making a PR. I could either:
1. Extract the photo from the archived tweet and add it to the repo. Then link to that picture.
2. Link directly to the tweet in archive.org
3. Delete the link entirely

Let me know that you think is best

**Comment by vprelovac** [comment]
I am fine with deleting the reference. Wdyt?
