### ISSUE TITLE
Kagi Docs for Browser Integration are Out of Date

### ISSUE THREAD

**Issue by hoffination** [kagisearch/kagi-docs#149]
### Relevant Page(s)

https://help.kagi.com/kagi/getting-started/setting-default.html#chromium_browsers

### Description

Testing these steps out in Opera and Chrome doesn't work for me.

Those browsers seem to be locked down to even reject changes when made manually: https://forums.opera.com/topic/32795/can-t-set-custom-search-engine-as-default/20

Hoping that there's a way for this to be the default search engine without needing to specify a `k` command. Using Alfred has been great though, and that should get me through until there's another option.

I really like Orion, but I need a workspace solution like Opera provides to help me manage my tabs

**Comment by david-ros** [comment]
HI @hoffination , we will revise the docs, in the meantime have you tried installing Kagi's web browser extension?

https://chrome.google.com/webstore/detail/kagi-search-for-chrome/cdglnehniifkbagbbombnjghhcihifij

**Comment by hoffination** [comment]
Thanks @david-ros !
I have been able to download and it works great in Chrome but doesn't seem to be working in Opera. I can summarize pages but it doesn't seem to update the default browser.

**Comment by david-ros** [comment]
Hi @hoffination ,
I'm able to reproduce the issue with Opera not changing the search engine used in the address bar after installing the Kagi extension. It seems that Opera is forcing users to use one of the predefined search engines, as I tried installing the Qwant extension and it is not changing the default search engine either. I recommend you contact Opera and request them to let users choose alternative search engines or add Kagi to their list of default search engines in the link below:

https://opera.atlassian.net/servicedesk/customer/portal/9

Thanks!

**Comment by david-ros** [comment]
Closing this issue as a note has been added to the documentation about Opera no longer being compatible, we found it possible to manually set Kagi as a search engine in other Chromium browsers.
https://help.kagi.com/kagi/getting-started/setting-default.html#opera_extension
