### ISSUE TITLE
Color contrast of links in light mode does not conform to WCAG

### ISSUE THREAD

**Issue by KyleErhabor** [kagisearch/kagi-docs#180]
### Relevant Page(s)

https://help.kagi.com/kagi

### Description

When reading about [Kagi's $10/mo unlimited search plan](https://blog.kagi.com/unlimited-searches-for-10), I went to the [docs for setting the default browser](https://help.kagi.com/kagi/getting-started/setting-default.html) and noticed it was somewhat difficult to differentiate the links from the background due to the contrast. I used the [Pika app](https://superhighfives.com/pika) to measure the colors and found white (#FFFFFF) for the background and imperial yellow (#F4B544) for the link text, giving it a contrast ratio of 1.82. This greatly misses the mark for [WCAG's color contrast standard](https://webaim.org/resources/contrastchecker/?fcolor=F4B544&bcolor=FFFFFF), which is a general target for accessibility (they recommend at least 3:1).

In dark mode, the colors are a lot clearer to see, but I think a deeper shade of orange would help for people like me who don't always use it.

**Comment by vprelovac** [comment]
@KyleErhabor Thanks for bringing ths up. @david-ros can you try a couple of different versions using colors from our palette at https://kagi.com/assets ?
