### ISSUE TITLE
Broken FAQ link on pricing page

### ISSUE THREAD

**Issue by techknight** [kagisearch/kagi-docs#242]
### Relevant Page(s)

https://kagi.com/pricing

### Description

At the bottom of Kagi's [pricing page](https://kagi.com/pricing), under "I have more questions!", there's a broken link to the FAQ.

Markdown with broken link:
`See our [FAQ](https://help.kagi.com/kagi/company/faqs.html) or feel free to reach out at [support@kagi.com](mailto:support@kagi.com).`

Fixed version:
`See our [FAQ](https://help.kagi.com/kagi/faq/faq.html) or feel free to reach out at [support@kagi.com](mailto:support@kagi.com).`

I'm adding this as an issue here because it concerns documentation, but technically the kagi.com pages fall outside the scope of the kagi-docs repo. (Otherwise I'd just create a PR 😅)

**Comment by vprelovac** [comment]
Thanks, should be addressed today!
