### ISSUE TITLE
Pricing outage has wrong why pay link

### ISSUE THREAD

**Issue by Hoovs** [kagisearch/kagi-docs#252]
### Relevant Page(s)

https://kagi.com/pricing

### Description

https://kagi.com/pricing has what I assume was a changed url. During the update the pricing page was missed. If you go to pricing, under faq, “why should I pay for search?” The URL is https://help.kagi.com/kagi/why-kagi/why-pay.html
But should be https://help.kagi.com/kagi/faq/faq.html#why-should-i-pay-for-search

I assume this happened when it moved from a dedicated page.

Thanks got the engine and the help.

**Comment by vprelovac** [comment]
Thanks for the heads up! Will be fixed with next deploy.
