### ISSUE TITLE
Mac OS: Managing Extensions

### ISSUE THREAD

**Issue by coreyrr** [kagisearch/kagi-docs#303]
### Relevant Page(s)

https://help.kagi.com/orion/browser-extensions/macos-extensions.html#managing-extensions

### Description

Where is Window > Extensions?
<img width="731" alt="Screenshot 2023-11-25 at 05 31 43" src="https://github.com/kagisearch/kagi-docs/assets/3230279/d8fc9e93-5d60-4f35-a6fa-5cf60061a348">

**Comment by gastonmorixe** [comment]
I think it's under Tools now 

<img width="659" alt="image" src="https://github.com/kagisearch/kagi-docs/assets/637225/18289a83-8578-4a56-9181-40076af6407f">

Version 0.99.126.3-beta (WebKit 618.1.2)
Build date Nov 20 2023
MacBook Pro (macOS Sonoma 14.1.1 build 23B81)

**Comment by vprelovac** [comment]
Docs should be updated

**Comment by david-ros** [comment]
@vprelovac Docs have been updated
