### ISSUE TITLE
Ambiguity in wording on "Why pay for search" after Google founders quote

### ISSUE THREAD

**Issue by daniels** [kagisearch/kagi-docs#306]
### Relevant Page(s)

https://help.kagi.com/kagi/why-kagi/why-pay-for-search.html#ad-supported-search-engines-the-future-of-the-web

### Description

From the page (my emphasis and reference numbers):

> In the early days of Google, in 1998, its founders rightly recognized that **it is an imperative for a search engines to remain ad-free**<sup>(1)</sup>:
>
> > [---]
> > For this type of reason and historical experience with other media [Bagdikian 83], **we expect that advertising funded search engines will be inherently biased towards the advertisers and away from the needs of the consumers**<sup>(2)</sup>"
> > — [The Anatomy of a Large-Scale Hypertextual Web Search Engine](http://infolab.stanford.edu/pub/papers/google.pdf), Sergey Brin and Lawrence Page, 1998
>
> **Unfortunately, this is not how it played out**<sup>(3)</sup>, and over the last 20 years we proceeded to witness the [great detoriation of web and search](https://blog.kagi.com/age-pagerank-over) as a result.

I assume that (3) is meant to refer back to (1) but to me when read in context it seems to refer back to (2), which makes it a surprising and arguably false statement.

(Note also that (1) does not correctly summarize the quote, but either refers to the context in the source outside of the quote or interprets the quote and draws its own conclusion.)

I would probably change (3) to "Unfortunately, this is *exactly* how it played out", and possibly change (1) to better reflect what is actually said in the quote.

(Also, there is a typo in (1): "a search engines" mixes singular and plural.)

**Comment by vprelovac** [comment]
Thanks for the detailed analysis. It makes sesne - made the changes.
