### ISSUE TITLE
Next page button links to the current page rather than the next one

### ISSUE THREAD

**Issue by gavinfoley** [kagisearch/kagi-docs#31]
### Relevant Page(s)

- https://help.kagi.com/kagi/getting-started/index.html
- https://help.kagi.com/kagi/plans/plan-types.html

### Description

If you open one of the links above, a large, clickable right-facing arrow is shown on the right side of the page.  When clicked, it's meant to navigate to the next page.  It works as expected for most pages, but not for some, including the pages I've linked.

The reason seems to be that the relevant pages are linked to twice:

```md
- [Getting Started](./getting-started/index.md)
	- [Quick Start](./getting-started/index.md)
```
```md
- [Plans & Payment](./plans/plan-types.md)
	- [Plan Types](./plans/plan-types.md)
```
([source](https://github.com/kagisearch/kagi-docs/blob/0fd9740857ed09130738e79fe5132606d0909edb/kagi/src/SUMMARY.md?plain=1#L37))

My guess is that mdBook simply links one page's next button to the next page in the list, so if the next page in the list is the same as the current page, the current page links to itself.

**Comment by rmschindler** [comment]
FYI, this same issue is observed here: [help.kagi.com/orion/company/index.html](https://help.kagi.com/orion/company/index.html).

**Comment by vprelovac** [comment]
@david-ros can you take a look at this?

**Comment by david-ros** [comment]
Hi @gavinfoley, @vprelovac, @z64. This issue is resolved now, we can close this issue.

**Comment by gavinfoley** [comment]
Looks like that was PR #112  - thank you!
