### ISSUE TITLE
Search field steals focus when up/down arrow key is pressed

### ISSUE THREAD

**Issue by Expurple** [kagisearch/kagi-docs#367]
### Relevant Page(s)

Any page in https://help.kagi.com/kagi

### Description

When I try to scroll documentation pages using the up/down arrow keys, they always switch focus to the search field at the top of the page (the one that says "Search or ask me anything..."), instead of scrolling like on any other web page. This is incredibly annoying. This happens always, even when the page contents are obviously focused before the key press, e.g. if I selected some text using the mouse or clicked on a section anchor.

PgUp/PgDn keys work as expected.

**Comment by ben476** [comment]
Hey @Expurple, this is now fixed.
