### ISSUE TITLE
Clarify the localized sales tax notice

### ISSUE THREAD

**Issue by gabfv** [kagisearch/kagi-docs#379]
### Relevant Page(s)

https://help.kagi.com/kagi/plans/plan-types.html

### Description

Hi!
I just wanted to share that for the sales tax notice, I received a "Reach Kagi +[some number]ABCA" 0$ authorization on March 26th 2024 on my credit card, despite having subscribed before that date:
https://github.com/kagisearch/kagi-docs/blob/b9f94f70b3355778f9bbca0e6d0cff04544f9218/docs/kagi/plans/plan-types.md?plain=1#L9
Sadly, searching "Reach Kagi" or the following number in the transaction's description did not yield useful results on the web. To add to the confusion, there seems to be a spa named Kagi Maldives which came up in the results.
Maybe clarify in the notice that the authorization will come from "Reach Kagi" until a proper name/description (like the same "Kagi.com" I had when I subscribed) is fixed for the sales tax authorization?

Hopefully, that'll help somebody else who is curious about the authorization on their payment type!

**Comment by david-ros** [comment]
@gabfv We added a new page focused on the sales tax implementation, one of the questions addresses this question:
https://help.kagi.com/kagi/faq/sales-tax-vat.html
