### ISSUE TITLE
typo (lense should be lens)

### ISSUE THREAD

**Issue by kslays** [kagisearch/kagi-docs#419]
### Relevant Page(s)

https://help.kagi.com/kagi/faq/faq.html#how-are-searches-counted

### Description

Each [lense](https://help.kagi.com/kagi/features/lenses.html) and content type (e.g. images, news) is considered a separate search.

Should be:

Each [lens](https://help.kagi.com/kagi/features/lenses.html) and content type (e.g. images, news) is considered a separate search.

**Comment by david-ros** [comment]
Hi @kslays, thanks for catching this typo. This has been fixed.
