### ISSUE TITLE
Instant Answers does not show up for example query

### ISSUE THREAD

**Issue by jonas-w** [kagisearch/kagi-docs#420]
### Relevant Page(s)

https://github.com/kagisearch/kagi-docs/blob/571b22f6109fb25a2e0e8ff601311ff3d3a5e1b1/docs/kagi/settings/search.md?plain=1#L30

### Description

The query does not yield an instant answer, only a wikipedia widget.

Someone on Discord was misled by this, and  thought that the Wikipedia Box has something to do with AI.

https://discord.com/channels/849884108750061568/908111790339149835/1247414057968078913

https://discord.com/channels/849884108750061568/908111790339149835/1247504934375788585

Maybe it's better to use a screenshot here.

**Comment by david-ros** [comment]
What @jonas-w mentions is correct. Instant answers has been disabled in favor of Quick Answer. We don't talk about Instant Answers in the docs so don't see a need to make changes there.

**Comment by david-ros** [comment]
@jonas-w I have now removed that text from the documentation. Thanks for pointing it out.
