### ISSUE TITLE
Highlight that Unlimited users may be limited to 500 AI interactions per month

### ISSUE THREAD

**Issue by bllooi** [kagisearch/kagi-docs#424]
### Relevant Page(s)

https://help.kagi.com/kagi/ai/kagi-ai.html

### Description

Unfortunately I find that having the line

> Fair Use Policy In an effort to provide services to everyone, we may limit interactions with our AI tools to 500 interaction per month for the Unlimited plan users. 

In the TOS [https://kagi.com/privacy] only is a bit misleading. I don't doubt that maybe this fact was just missed out but I think it should really be highlighted to Ultimate users.

I understand that AI use needs to be paid for. I don't mind paying more. 

However, please warn me, appropriately in the AI docs, beforehand that my account may be limited in the case that I have hit this 500 interaction mark and tell me how I may find out how much I have already used. 

I use the quick answer extremely regularly and it would really suck to loose this feature. If you could let me pay for more interactions that would be super helpful as well.

I'm also a bit confused on the definition of AI tools (Assistant only? Summarizer and Quick Answer included?). And the TOS mentions Ultimate users only. Maybe TOS needs updating?

Been loving my time on kagi otherwise. <3

**Comment by Esras** [comment]
I think this is related to my question / issue...

So the docs page for the plans describes the Professional plan as simply offering unlimited searches. The [Billing Settings page](https://kagi.com/settings?p=billing_plan) describes the plan as having "Unlimited access to FastGPT and Universal Summarizer." When trying to look up the potential cost of those tools, the docs pages mention that it utilizes API credits and a link to add credits.

What's not clear to me is whether or not you still need to pay for those credits at the Professional level (or the Ultimate level, either). The [Ultimate Plan doc page](https://help.kagi.com/kagi/plans/ultimate-plan.html) mentions discounted access to those tools.

I think I'm just looking for a bit of clarification on the pricing. I also understand things are in flux. Thanks for a great product!

**Comment by bllooi** [comment]
Hey @Esras , at the ultimate level I haven't needed to pay extra for the credits. **There are per entry  limits to these tools** described by:

>  Assistant has a character limit of 16,000 for each prompt in a conversation.

Regarding my issue above, I did reach out to kagi support and received the reply below:

> We have this fair use policy mostly to protect ourselves from abuse however we are not currently enforcing it.
> You can continue using those tools as usual, we want those tools to feel unlimited but just don't want someone to create a bot and go above what a normal user would use.

From what it seems, there is _effectively_ no limit. This is a bit scary tbh, idk how they're breaking even 😅. Maybe the 25 usd a month really does cover it.

**Comment by david-ros** [comment]
Closing this issue as @bllooi cited response from Kagi Support which answers the original question.
