### ISSUE TITLE
Bad link in Community Add-ons

### ISSUE THREAD

**Issue by arnaldop** [kagisearch/kagi-docs#425]
### Relevant Page(s)

https://help.kagi.com/kagi/community-addons/#script-kit

### Description

The link to [FastGPT for Script Kit](https://scriptkit.com/api/new?name=kagi-fastgpt&url=https://gist.githubusercontent.com/awakenedhaggis/bd9dbf2421325117f7e5c20f62e1c99f/raw/9ab7d843fdfb2bf3b1e3c65e5c4774fe896abc91/kagi-fastgpt.ts) does not work.

I was also not able to find the file `kagi-fastgpt.ts` in the Kagi Docs repo (official or `awakenedhaggis`).

**Comment by david-ros** [comment]
@arnaldop I tried the link and it tries to redirect me to the following URL scheme:
kit:new?name=kagi-fastgpt&url=https://gist.githubusercontent.com/awakenedhaggis/bd9dbf2421325117f7e5c20f62e1c99f/raw/9ab7d843fdfb2bf3b1e3c65e5c4774fe896abc91/kagi-fastgpt.ts

I also see that the file kagi-fastgpt.ts does exist in the URL that is being called  https://gist.githubusercontent.com/awakenedhaggis/bd9dbf2421325117f7e5c20f62e1c99f/raw/9ab7d843fdfb2bf3b1e3c65e5c4774fe896abc91/kagi-fastgpt.ts

So it seems to me that the link will work but only for those that have script kit installed. Did you have it installed when you tried the link?

**Comment by david-ros** [comment]
I downloaded ScriptKit and tested the link and it is working correctly. Closing this issue.

**Comment by arnaldop** [comment]
I installed ScriptKit, restarted the Mac, and still have a problem.

Clicking on the link takes me to `kit:new?name=kagi-fastgpt&url=https://gist.githubusercontent.com/awakenedhaggis/bd9dbf2421325117f7e5c20f62e1c99f/raw/9ab7d843fdfb2bf3b1e3c65e5c4774fe896abc91/kagi-fastgpt.ts`, which gives me this:

![image](https://github.com/kagisearch/kagi-docs/assets/6642062/6b342584-a4b9-4ff0-bded-20016f34751a)

Perhaps I did something wrong, but I don't know where to start looking. Thx
