### ISSUE TITLE
Link for Chromium-based browsers extension returns 404

### ISSUE THREAD

**Issue by hacdias** [kagisearch/kagi-docs#484]
### Relevant Page(s)

https://help.kagi.com/kagi/getting-started/setting-default.html#browser_extension

### Description

The link for Chromium-based browsers extension returns a 404: https://chrome.google.com/webstore/detail/cdglnehniifkbagbbombnjghhcihifij.

**Comment by erics118** [comment]
See https://github.com/kagisearch/browser_extensions/issues/84

**Comment by hacdias** [comment]
Thanks for the link! I will close this one.
