### ISSUE TITLE
This part contains incorrect information

### ISSUE THREAD

**Issue by hexWars** [kagisearch/kagi-docs#499]
### Relevant Page(s)

[https://help.kagi.com/kagi/faq/faq.html#where-can-i-find-examples-of-custom-css-created-by-other-users](https://help.kagi.com/kagi/faq/faq.html#where-can-i-find-examples-of-custom-css-created-by-other-users)

### Description

In the description, I didn’t see the #appearance channel.

**Comment by laizxyz** [comment]
Fixed in #548
