### ISSUE TITLE
Themes referenced in docs aren't available in the UI

### ISSUE THREAD

**Issue by IlyaBizyaev** [kagisearch/kagi-docs#503]
### Relevant Page(s)

https://help.kagi.com/kagi/settings/appearance.html

### Description

None of these themes:

* Calm Blue
* Fine Print
* Royal Blue
*  Moon Dark

— are available in settings. All I have are Kagi Light/Dark and Old School Light/Dark.

**Comment by thibaultmol** [comment]
@david-ros this can be closed i think
